        /* Shared utilities general include header file.*/

	#ifndef _rtw_shared_utils_h_
	# define _rtw_shared_utils_h_
	
        #include "mul_wide_s32.h"
        #include "BINARYSEARCH_S8.h"
        #include "BINARYSEARCH_U16.h"
        #include "BINARYSEARCH_U8.h"
        #include "BINARYSEARCH_U8_iL.h"
        #include "INTERPOLATE_S8_U16.h"
        #include "INTERPOLATE_S8_U8.h"
        #include "INTERPOLATE_U16_S16.h"
        #include "INTERPOLATE_U16_U16.h"
        #include "INTERPOLATE_U16_U8.h"
        #include "INTERPOLATE_U8_S8.h"
        #include "INTERPOLATE_U8_U16.h"
        #include "INTERPOLATE_U8_U8.h"
        #include "Look2D_S8_U8_U8.h"
        #include "Look2D_U16_U16_U16.h"
        #include "Look2D_U16_U8_U16.h"
        #include "Look2D_U16_U8_U8.h"
        #include "Look2D_U8_U8_U8.h"
        #include "LookUp_S8_U16.h"
        #include "LookUp_S8_U8.h"
        #include "LookUp_U16_S16.h"
        #include "LookUp_U16_U16.h"
        #include "LookUp_U16_U8.h"
        #include "LookUp_U8_S8.h"
        #include "LookUp_U8_U16.h"
        #include "LookUp_U8_U8.h"
        #include "TuneParamCast_S16_U8_SL8_SAT.h"
        #include "binsearch_u8u16.h"
        #include "binsearch_u8u8.h"
        #include "div_repeat_u32_sat.h"
        #include "div_s16_floor.h"
        #include "div_s16_sat_floor.h"
        #include "div_s32_floor.h"
        #include "div_s8s16_floor.h"
        #include "div_s8s32_floor.h"
        #include "div_u16.h"
        #include "div_u16_SR.h"
        #include "div_u32.h"
        #include "intrp1d_u16u8u16n15_lca_f.h"
        #include "intrp1d_u8u8u16n15_lca_f.h"
        #include "intrp2d_s8u8u16n15_lca_f.h"
        #include "intrp2d_u16u8u16n15_lca_f.h"
        #include "intrp2d_u8u8u16n15_lca_f.h"
        #include "mul_s32_s32_s32_sat.h"
        #include "mul_u32_u32_u32_sat.h"
        #include "mul_u32_u32_u32_sr31_sat.h"
        #include "mul_u32_u32_u32_sr6_sat.h"
        #include "BINARYSEARCH_S16.h"
        #include "mul_wide_u32.h"
        #include "plook_u8u16_bincka.h"
        #include "plook_u8u16u16n15_binca_f.h"
        #include "plook_u8u8u16n15_binca_f.h"
        #include "rtwtypes.h"
	
	#endif /* _rtw_shared_utils_h_ */
